version: "3"
services:

  tfcactus:
    container_name: tfcactus
    build: .
    ports:
      - 10000:8888
      - 16006:6006
    hostname: "tfcactus"
    security_opt:
      - seccomp:unconfined
    volumes: 
      - ../src:/home/jovyan/work
    environment:
      - PASSWORD=foobar
      - JUPYTER_ENABLE_LAB=yes